### ISSUE TITLE
Umbrella Phase 2 requirements

### ISSUE THREAD

**Issue by elijahbenizzy** [DAGWorks-Inc/burr#113]
Follow up on #31. Goal is before or during `Show HN` launch. This is in priority order:

- [ ] Annotations, tagging, querying https://github.com/DAGWorks-Inc/burr/issues/46
    - [ ] Add programmatic API
    - [ ] Add UI annotation capability
    - [ ] Add querying capability programmatically
- [ ] Improve UI layout https://github.com/DAGWorks-Inc/burr/issues/100
- [ ] Simplify examples
    - [ ] Ensure everyone has README with the same structure 
        - [ ] What does this teach you
        - [ ] What should you know before
        - [ ] How to run
        - [ ] How to adapt to your case
    - [ ] Separate Hamilton from others
- [ ] Add control-flow-based documentation https://github.com/DAGWorks-Inc/burr/issues/56
- [ ] Add web-server based example documentation https://github.com/DAGWorks-Inc/burr/issues/22
- [ ] Add artifact logging

**Comment by skrawcz** [comment]
Something to add to the UI:

 - show a modal/way to show new lines in the strings that are captured.

**Comment by andreahlert** [comment]
Labels migrated to new taxonomy (#692).

**Comment by andreahlert** [comment]
Most items completed. Remaining sub-tasks tracked individually (#56, #46). Closing this umbrella as superseded.
