### ISSUE TITLE
Burr UI

### ISSUE THREAD

**Issue by elijahbenizzy** [DAGWorks-Inc/burr#16]
# Design
See doc here: https://docs.google.com/document/d/1dMjZSj2j3nl0JWF17q1oAcxXcBa4uKH5mxm9hsMG9xM/edit#heading=h.wkfjshpmk28

# Tasks:

## [Client](https://github.com/DAGWorks-Inc/burr/pull/18)
- [x] Implement client
- [ ] Implement async client
- [x] Decide on schema + pydantic models

## Server

FastUI + websockets for streaming updates. All `async`.

- [x] Implement endpoints
    - [x] `GET` /projects
    - [x] `GET` /project/{project_id}/runs
    - [x] `GET` /project/{project_id}/{run_id}` 
- [ ] Implement web sockets or server-sent events to allow for refreshing/streaming (should be straightforward)
- [x] Add some simple abstraction to allow for new backends 
- [ ] Add some very basic tests

## UI

React + tailwind components. See [license](https://tailwindui.com/license) for allowance of OS.
- [x] Get started 
    - [x] CRA to get a react app going 
    - [x] Tie it together to serve a static route through fastAPI
    - [x] Investigate whether we can develop efficiently with auto-updates
- [x] Header
- [x] Title 
- [x] Project select page
- [x] Project runs page
- [x] Trace runs page
    - [x] Viz using reactflow
    - [x] Action + action delta
    - [x] Replay button (optional)
    - [x] (auto) Update toggle/refresh
    
## demo (optional for now)

- [ ] Docker image with a bunch of examples loaded
- [ ] Deploy at `demo.burr.dagworks.io`
