### ISSUE TITLE
Umbrella V0 requirements

### ISSUE THREAD

**Issue by elijahbenizzy** [DAGWorks-Inc/burr#29]
For V0 release. Goal is next monday. User story:

1. Download `burr` from `pypi`
2. Run server
3. Check out demos
4. Copy/paste app 
5. Add something/modify
6. Track through server

Requirements:
- [x] Fix this issue: https://github.com/DAGWorks-Inc/burr/issues/28 -see https://github.com/DAGWorks-Inc/burr/pull/34
- [x] Get demo of Burr runs as a CLI `burr-demo chatbot`
    - [x] Demo data for each one
    - [x] Chatbot sample runs
    - [x] Counter example
    - [x] RAG
- [x] Merge all other examples
    - [x] https://github.com/DAGWorks-Inc/burr/pull/23
    - [x] https://github.com/DAGWorks-Inc/burr/pull/12
    - [x] https://github.com/DAGWorks-Inc/burr/pull/25
- [x] Test out installing/running
    - [x] Mac
    - [ ] Windows
- [x] Fix `run` API (`halt_before`/`halt_after`)
- [x] Release `0.3.0` (with server)
- [x] Release `0.4.0` (with all the other changes)
- [x] Add Roadmap to README (https://github.com/DAGWorks-Inc/burr/pull/38)
- [x] Fix serialization for tracking (https://github.com/DAGWorks-Inc/burr/pull/23)
- [x] [Add guards around installation](https://github.com/DAGWorks-Inc/burr/pull/32) 
- [x] Remove error case from chatbot example 
- [x] Add temporary "getting started with the UI" -- load up streamlit, open UI, see it work...
- [x] #36 (solved by #37)
- [x] Loom for explanation
- [x] Update docs to be public-facing #41

**Comment by elijahbenizzy** [comment]
Still need a windows test but I'm calling this done
