### ISSUE TITLE
Umbrella Phase 1 Requirements

### ISSUE THREAD

**Issue by elijahbenizzy** [DAGWorks-Inc/burr#31]
For V1 release. Goal is March 1. In addition to: https://github.com/DAGWorks-Inc/burr/issues/29, we have:
- [x] Example apps with tracking server
    - [x] Chatbot
 - [x] Add more complex example (simple chatbot) in getting started in docs
 - [x] Get video intro for those who want to watch
 - [x]  Roadmap in README 
 - [ ] (stretch) Static server hosted online
 - [x] Streamed output https://github.com/DAGWorks-Inc/burr/issues/19
 - [ ] (stretch, with feedback) -- handling exceptions (https://github.com/DAGWorks-Inc/burr/issues/30)
 - [x] State persistence in a clean way
 - [ ] (directly post-release) Logging metadata -- https://github.com/DAGWorks-Inc/burr/issues/46
 - [x] Telemetry/tracking on posthog (with opt-out, same as hamilton)(https://github.com/DAGWorks-Inc/burr/issues/58)
 - [x] Figure out what slack to link to
 - [x] Add comparison matrix in README #76 
     - [x] Langgraph
     - [x] Temporal
     - [x] langchain
     - [x] hamilton
     - [x] superagent.sh (burr is not agent specific, host/run wherever python runs)
- [x] Change README gif to be of actual chatbot API

**Comment by elijahbenizzy** [comment]
This is complete
