### ISSUE TITLE
Typed State Umbrella Issue

### ISSUE THREAD

**Issue by elijahbenizzy** [DAGWorks-Inc/burr#386]
For getting typed-state up to parity with standard state. Currently a list but these should be individual issues. 

Please comment with more!

- [ ] Documentation on differences between using pydantic/not
- [ ] Wiring through to serialization/persistence
    - [ ] Ensuring you can access `.data`
    - [ ] Type-hinting the persister class for custom stuff
- [ ] Serializing using the pydantic serializer
    - [ ] See [this comment](https://discord.com/channels/1221891403253288970/1221892061842772018/1291795622525010052)

**Comment by andreahlert** [comment]
Labels migrated to new taxonomy (#692).
