### ISSUE TITLE
Usability/debugging (umbrella)

### ISSUE THREAD

**Issue by elijahbenizzy** [DAGWorks-Inc/burr#88]
From user-feedback:
- [x] Result has to be a dictionary, this is confusing. Options:
    - [x] Error out if the result is not a dictionary -- this is the best for now
    - [ ] Wrap it in the dictionary
    - [ ] Relax the restriction?
- [x] Error out if a step does not produce the items in state you are expecting it to
    - [x] Anything in `write` must exist
- [x] People think state is mutable.

**Comment by elijahbenizzy** [comment]
This is complete for now -- the original issues have been addressed
