### ISSUE TITLE
Persister Umbrella Issue

### ISSUE THREAD

**Issue by skrawcz** [DAGWorks-Inc/burr#95]
- [x] Add Mongodb support
- [ ] Add snowflake support (this will likely be restrictive)
- [ ] Add deltalake support (this will likely be restrictive)
- [ ] Think through schema versioning patterns and provide guidance for upgrades & updates.

**Comment by andreahlert** [comment]
Labels migrated to new taxonomy (#692).
